version: '3.7'
services:
  app-1:
    container_name: app-1
    image: app-1:1.0.0
    environment:
      - PORT=4001
    ports:
      - 4001:4001
    network_mode: bridge
    env_file: prod.env
  app-2:
    container_name: app-2
    image: app-2:1.0.0
    environment:
      - PORT=4002
    ports:
      - 4002:4002
    network_mode: bridge
    volumes:
      - ./test.json:/usr/share/test.json
    env_file: prod.env